models:
  root_model:
    hid_ds: [11, 128, 128, 256, 256, 128]
  head_models:
    hid_ds: [128, 128, 256, 256, 128]

data:
  dataset_names: ['BBB_Martins']
   #['hERG', 'AMES', 'DILI', 'Carcinogens_Lagunin', 'ClinTox', 'LD50_zhu']
  dataset_params:
    balance_labels: True
    oversample: True # if false undersamples unbalance classes
    split_size: [0.8, 0.1, 0.1]
    use_coords: False
    atom_features: ['atomic_mass', 'implicit_valence', 'explicit_valence', 'formal_charge', 'hybridization', 'is_aromatic', 'is_isotope', 'chiral_tag', 'vocab_idx']
    bond_features: ['bond_type', 'is_aromatic', 'is_conjugated', 'bond_stereo']
  dataloader_params:
    shuffle: True
    batch_size: 512
    pin_memory: True
    num_workers: 4

train:
  epochs: 35
  finetune_epochs: 0
  val_n_steps: 5
  log_n_steps: 5
  optimizer_params:
    lr: 1.0e-4
    betas: [0.9, 0.999]
  scheduler_params:
    gamma: 0.9
    step_size: 5
    min_lr: 5.0e-6
    
  freeze_root: Tue
  root_model_path: /home/j/Desktop/Programming/deep_pharma/saved_models/adme/root_model.pth
  device: 'cuda:0'